# Generated by Django 4.0.4 on 2022-04-22 12:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('interior_image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('interior_image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('interior_image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('interior_image_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('interior_image_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_5', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('ratings', models.CharField(blank=True, max_length=250, null=True)),
                ('map', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price_per_night', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, choices=[('Standard', 'Standard'), ('Low Cost', 'Low Cost'), ('Luxury', 'Luxury')], max_length=100, null=True)),
                ('listed_on', models.DateField(default=datetime.datetime(2022, 4, 22, 12, 38, 41, 38501, tzinfo=utc))),
                ('no_of_bedrooms', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=250, null=True)),
                ('no_of_bathrooms', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=250, null=True)),
                ('no_of_guests', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=250, null=True)),
                ('wifi', models.BooleanField(blank=True, null=True)),
                ('air_condition', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('service_type', models.CharField(blank=True, choices=[('Apartments and hotels', 'Apartments and hotels'), ('Cars and Automobiles', 'Cars and Automobiles')], max_length=250, null=True)),
                ('business_name', models.CharField(blank=True, max_length=250, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked', models.BooleanField(default=False)),
                ('booking_date', models.DateField(default=datetime.datetime(2022, 4, 22, 12, 38, 41, 42426, tzinfo=utc))),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.apartments')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=250, null=True)),
                ('email_address', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=250, null=True)),
                ('number_of_bookings', models.CharField(blank=True, max_length=250, null=True)),
                ('date_created', models.DateField(default=datetime.datetime(2022, 4, 22, 12, 38, 41, 46682, tzinfo=utc))),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HostProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('mobile_number', models.CharField(blank=True, max_length=250, null=True)),
                ('email_address', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=250, null=True)),
                ('number_of_listings', models.CharField(blank=True, max_length=250, null=True)),
                ('date_created', models.DateField(default=datetime.datetime(2022, 4, 22, 12, 38, 41, 47570, tzinfo=utc))),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.host')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(max_length=250)),
                ('ratings', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Convertible', 'Convertible'), ('Truck', 'Truck')], max_length=100, null=True)),
                ('listed_on', models.DateField(default=datetime.datetime(2022, 4, 22, 12, 38, 41, 43472, tzinfo=utc))),
                ('bluetooth', models.BooleanField(blank=True, null=True)),
                ('air_condition', models.BooleanField(blank=True, null=True)),
                ('host', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.host')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('interior_image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('interior_image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('interior_image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('interior_image_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('interior_image_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cars')),
            ],
        ),
        migrations.AddField(
            model_name='apartments',
            name='host',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.host'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.apartmentmedia'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apartmentmedia',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.apartments'),
        ),
    ]
