# Generated by Django 4.0.4 on 2022-06-19 11:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 11, 8, 17, 858763, tzinfo=utc)),
        ),
    ]
