# Generated by Django 4.0.4 on 2022-06-19 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reservations_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 13, 3, 47, 882591, tzinfo=utc)),
        ),
    ]
