# Generated by Django 4.0.4 on 2022-04-22 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_apartments_listed_on_alter_cars_listed_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostprofile',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='listed_on',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 13, 34, 33, 172685, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cars',
            name='listed_on',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 13, 34, 33, 177447, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hostprofile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 13, 34, 33, 181657, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 13, 34, 33, 180737, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 13, 34, 33, 176499, tzinfo=utc)),
        ),
    ]
