# Generated by Django 4.0.4 on 2022-06-11 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hostprofile_country_alter_apartments_listed_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='listed_on',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 12, 9, 30, 585156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cars',
            name='listed_on',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 12, 9, 30, 589051, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hostprofile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 12, 9, 30, 592406, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 12, 9, 30, 591662, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 12, 9, 30, 588214, tzinfo=utc)),
        ),
    ]
