# Generated by Django 4.0.4 on 2022-06-11 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apartments_slug_alter_apartments_listed_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='listed_apartments',
            field=models.ManyToManyField(to='core.apartments'),
        ),
        migrations.AddField(
            model_name='profile',
            name='no_of_apartments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='listed_on',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 12, 17, 59, 403686, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cars',
            name='listed_on',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 12, 17, 59, 414613, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hostprofile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 12, 17, 59, 426669, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 12, 17, 59, 422681, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 12, 17, 59, 412417, tzinfo=utc)),
        ),
    ]
