# Generated by Django 4.0.4 on 2022-06-13 07:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('interior_image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('interior_image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('interior_image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('interior_image_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('interior_image_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_5', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('ratings', models.CharField(blank=True, max_length=250, null=True)),
                ('map', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price_per_night', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, choices=[('Standard', 'Standard'), ('Low Cost', 'Low Cost'), ('Luxury', 'Luxury')], max_length=100, null=True)),
                ('listed_on', models.DateField(default=datetime.datetime(2022, 6, 13, 7, 56, 21, 119449, tzinfo=utc))),
                ('no_of_bedrooms', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=250, null=True)),
                ('no_of_bathrooms', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=250, null=True)),
                ('no_of_guests', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=250, null=True)),
                ('wifi', models.BooleanField(blank=True, null=True)),
                ('air_condition', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(blank=True, max_length=250, null=True)),
                ('service_type', models.CharField(blank=True, choices=[('Apartments and hotels', 'Apartments and hotels'), ('Cars and Automobiles', 'Cars and Automobiles')], max_length=250, null=True)),
                ('host_user_name', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('mobile_number', models.CharField(blank=True, max_length=250, null=True)),
                ('email_address', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, default='Nigeria', max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=250, null=True)),
                ('date_created', models.DateField(default=datetime.datetime(2022, 6, 13, 7, 56, 21, 117208, tzinfo=utc))),
                ('no_of_apartments', models.IntegerField(blank=True, null=True)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hosts.host')),
                ('listed_apartments', models.ManyToManyField(to='hosts.apartments')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('location', models.CharField(max_length=250)),
                ('ratings', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Convertible', 'Convertible'), ('Truck', 'Truck')], max_length=100, null=True)),
                ('listed_on', models.DateField(default=datetime.datetime(2022, 6, 13, 7, 56, 21, 122376, tzinfo=utc))),
                ('bluetooth', models.BooleanField(blank=True, null=True)),
                ('air_condition', models.BooleanField(blank=True, null=True)),
                ('host', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.host')),
            ],
        ),
        migrations.CreateModel(
            name='CarMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('interior_image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('interior_image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('interior_image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('interior_image_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('interior_image_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('exterior_image_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.cars')),
            ],
        ),
        migrations.AddField(
            model_name='apartments',
            name='host',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.host'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.apartmentmedia'),
        ),
        migrations.AddField(
            model_name='apartmentmedia',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.apartments'),
        ),
    ]
