# Generated by Django 4.0.4 on 2022-06-19 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_rename_no_of_apartments_hostprofile_total_number_of_listed_apartments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentamenities',
            name='wifi',
        ),
        migrations.AddField(
            model_name='apartmentamenities',
            name='free_wifi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='apartmentamenities',
            name='heating',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='apartmentamenities',
            name='washing_machine',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentamenities',
            name='air_condition',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='listed_on',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 13, 51, 8, 192115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cars',
            name='listed_on',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 13, 51, 8, 194922, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hostprofile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 13, 51, 8, 190516, tzinfo=utc)),
        ),
    ]
