# Generated by Django 4.0.4 on 2022-06-19 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_id_alter_profile_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 13, 3, 47, 873621, tzinfo=utc)),
        ),
    ]
