# Generated by Django 4.0.4 on 2022-06-19 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 13, 51, 8, 188400, tzinfo=utc)),
        ),
    ]
